// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire gen -tags "local"
//+build !wireinject

package main

import (
	"github.com/vrealzhou/geekbang_go_course/week4/cmd/core/v1/initialize"
	"github.com/vrealzhou/geekbang_go_course/week4/internal/config"
	"github.com/vrealzhou/geekbang_go_course/week4/internal/todo"
	"github.com/vrealzhou/geekbang_go_course/week4/internal/todo/dao"
)

// Injectors from main.go:

func initDAO(cfg config.Config) (todo.DAO, error) {
	pgdao, err := dao.NewPGDAO(cfg)
	if err != nil {
		return nil, err
	}
	return pgdao, nil
}

// main.go:

func main() {
	cfg := initialize.InitConfig()
	dao2, err := initDAO(cfg)
	if err != nil {
		panic(err)
	}
	if i, ok := dao2.(todo.Initializer); ok {
		err := i.Init()
		if err != nil {
			panic(err)
		}
	}
}
